// Builds the opening book (js/bookdata.js): for the first few turns of the
// standard game, the turns a long Hard search likes best. Covers Blue's
// first edge, Red's reply to every possible first edge, and the next two
// turns along the book lines.
//
// node tools/book.mjs [threads] [timeScale]
import { Worker, isMainThread, parentPort } from 'node:worker_threads';
import { cpus } from 'node:os';
import { writeFileSync } from 'node:fs';

if (isMainThread) {
  const threads = Number(process.argv[2] || Math.max(1, cpus().length - 2));
  const timeScale = Number(process.argv[3] || 4);
  const { Game } = await import('../js/engine.js');
  const { positionKey } = await import('../js/book.js');
  const book = {};

  // Runs one search per position, spread over worker threads.
  async function searchAll(positions) {
    const results = new Array(positions.length);
    let next = 0;
    await new Promise((resolve) => {
      if (!positions.length) { resolve(); return; }
      let done = 0;
      for (let t = 0; t < Math.min(threads, positions.length); t++) {
        const w = new Worker(new URL(import.meta.url));
        const feed = () => { if (next < positions.length) { const i = next++; w.postMessage({ i, history: positions[i].history, timeScale }); } else w.terminate(); };
        w.on('message', (r) => {
          results[r.i] = r.plans;
          if (++done === positions.length) resolve();
          feed();
        });
        feed();
      }
    });
    return results;
  }

  const S = 19;
  function add(g, plans) {
    const { key, flip } = positionKey(g);
    book[key] = plans.map((p) => p.map(([fx, fy, tx, ty]) => [fx, flip ? S - 1 - fy : fy, tx, flip ? S - 1 - ty : ty]));
  }
  const after = (history, plan) => {
    const g = Game.fromHistory(history);
    for (const [fx, fy, tx, ty] of plan) g.play(fx, fy, tx, ty);
    return g.history.map(({ kind, fx, fy, tx, ty, player }) => ({ kind, fx, fy, tx, ty, player }));
  };

  // Depth 1: Blue's first edge.
  const start = new Game();
  const [first] = await searchAll([{ history: [] }]);
  add(start, first);
  process.stderr.write(`start: ${first.length} choices\n`);

  // Depth 2: Red's reply to every first edge (mirror images share a key).
  const replies = [];
  const seen = new Set();
  for (const m of start.legalMoves()) {
    const h = after([], [[m.fx, m.fy, m.tx, m.ty]]);
    const key = positionKey(Game.fromHistory(h)).key;
    if (seen.has(key)) continue;
    seen.add(key);
    replies.push({ history: h });
  }
  const replyPlans = await searchAll(replies);
  replies.forEach((p, i) => add(Game.fromHistory(p.history), replyPlans[i]));
  process.stderr.write(`replies: ${replies.length} positions\n`);

  // Depths 3 and 4: along the book lines only.
  const lookup = (g) => {
    const { key, flip } = positionKey(g);
    return (book[key] || []).map((p) => p.map(([fx, fy, tx, ty]) => [fx, flip ? S - 1 - fy : fy, tx, flip ? S - 1 - ty : ty]));
  };
  let frontier = [];
  for (const b of lookup(start)) {
    const h1 = after([], b);
    for (const r of lookup(Game.fromHistory(h1))) frontier.push({ history: after(h1, r) });
  }
  for (let depth = 3; depth <= 4; depth++) {
    const plans = await searchAll(frontier);
    const nextFrontier = [];
    frontier.forEach((p, i) => {
      add(Game.fromHistory(p.history), plans[i]);
      if (depth < 4) for (const pl of plans[i]) nextFrontier.push({ history: after(p.history, pl) });
    });
    process.stderr.write(`depth ${depth}: ${frontier.length} positions\n`);
    frontier = nextFrontier;
  }

  const keys = Object.keys(book).sort();
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(book[k])},`).join('\n');
  writeFileSync(new URL('../js/bookdata.js', import.meta.url), `// Generated by tools/book.mjs: turns a long Hard search picked for the
// first few turns of the standard game, keyed by position (see js/book.js).
export const BOOK = {
${body}
};
`);
  console.log(`${keys.length} positions in the book`);
} else {
  const { Game } = await import('../js/engine.js');
  const { planTurn, LEVELS } = await import('../js/ai.js');
  parentPort.on('message', ({ i, history, timeScale }) => {
    const g = Game.fromHistory(history);
    const cfg = { ...LEVELS.hard, noise: 0, budget: Math.round(LEVELS.hard.budget * timeScale) };
    const res = planTurn(g, cfg, 12345, { explain: true });
    const opts = res.options || [];
    const top = opts.length ? opts[0].value : 0;
    // The chosen turn, plus any near-equal alternative for variety.
    const plans = opts.filter((o, k) => k === 0 || (o.value !== undefined && o.value >= top - 0.5))
      .map((o) => o.plan.filter((m) => m.kind === 'edge').map((m) => [m.fx, m.fy, m.tx, m.ty]))
      .filter((p) => p.length === g.left);
    // The same edges in another order or direction are the same turn.
    const seen = new Set();
    const unique = plans.filter((p) => {
      const k = p.map(([a, b, c, d]) => (a < c || (a === c && b < d) ? [a, b, c, d] : [c, d, a, b]).join(',')).sort().join('|');
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    });
    parentPort.postMessage({ i, plans: unique });
  });
}
