// Turns mined (and verified) candidates into js/puzzledata.js.
// node tools/build-puzzles.mjs verified.json [more.json ...]
import { readFileSync, writeFileSync } from 'node:fs';

const all = [];
process.argv.slice(2).forEach((f, fi) => {
  for (const p of JSON.parse(readFileSync(f, 'utf8'))) all.push({ ...p, game: `${fi}:${p.game ?? 0}` });
});

// Within one game, keep positions at least 3 turns apart and never the same
// first edge twice, preferring the more interesting puzzle of a close pair.
const interest = (p) => (p.best - p.greedy) + (p.firsts <= 2 ? 3 : 0) + (p.cut > 0 && p.gain > 0 ? 2 : 0);
const byGame = new Map();
for (const p of all) {
  if (!byGame.has(p.game)) byGame.set(p.game, []);
  byGame.get(p.game).push(p);
}
const kept = [];
const seenCodes = new Set();
for (const list of byGame.values()) {
  list.sort((a, b) => interest(b) - interest(a));
  const chosen = [];
  for (const p of list) {
    if (seenCodes.has(p.code)) continue;
    const first = p.sol[0].join(',');
    const close = (q) => q.turn !== undefined && p.turn !== undefined && Math.abs(q.turn - p.turn) < 3;
    if (chosen.some((q) => close(q) || q.sol[0].join(',') === first)) continue;
    chosen.push(p);
    seenCodes.add(p.code);
  }
  kept.push(...chosen);
}

// Easier: several different first edges reach the best. Harder: one pair
// does it, and it both fences in area and cuts, or the swing is large.
const level = (p) => {
  if (p.firsts > 2) return 1;
  if ((p.gain > 1e-9 && p.cut > 1e-9) || p.best >= 15) return 3;
  return 2;
};
kept.sort((a, b) => level(a) - level(b) || a.best - b.best);

const out = kept.map((p) => ({
  code: p.code, player: p.player, best: p.best, gain: p.gain, cut: p.cut, firsts: p.firsts, level: level(p), sol: p.sol,
}));
writeFileSync(new URL('../js/puzzledata.js', import.meta.url), `// Generated by tools/build-puzzles.mjs from mined positions. Every best
// swing was confirmed by tools/verify-puzzles.mjs, which tries every pair of edges.
export const PUZZLES = ${JSON.stringify(out, null, 0).replace(/\},\{/g, '},\n  {').replace(/^\[\{/, '[\n  {').replace(/\}\]$/, '},\n]')};
`);
console.log(`${all.length} candidates, ${out.length} puzzles (${[1, 2, 3].map((l) => out.filter((p) => level(p) === l).length).join(' / ')} by level)`);
