// Turns mined (and verified) candidates into js/puzzledata.js.
// node tools/build-puzzles.mjs verified.json [more.json ...]
// Puzzles already in js/puzzledata.js keep their place at the front of the
// list, so links to them keep working; new ones are added after them.
import { readFileSync, writeFileSync } from 'node:fs';

const { PUZZLES: existing } = await import('../js/puzzledata.js');

const all = [];
process.argv.slice(2).forEach((f, fi) => {
  for (const p of JSON.parse(readFileSync(f, 'utf8'))) all.push({ type: 'swing', ...p, game: `${fi}:${p.game ?? 0}` });
});

const typeOf = (p) => p.type || 'swing';

// Within one game, keep positions at least 3 turns apart and never the same
// first edge twice, preferring the more interesting puzzle of a close pair.
const interest = (p) => {
  const t = typeOf(p);
  if (t === 'block') return (p.worst - p.best) + (p.count <= 2 ? 3 : 0);
  if (t === 'plan') return 10 + (p.best - p.greedy);
  return (p.best - p.greedy) + (p.firsts <= 2 ? 3 : 0) + (p.cut > 0 && p.gain > 0 ? 2 : 0);
};
const byGame = new Map();
for (const p of all) {
  if (!byGame.has(p.game)) byGame.set(p.game, []);
  byGame.get(p.game).push(p);
}
const seenCodes = new Set(existing.map((p) => p.code));
const fresh = [];
for (const list of byGame.values()) {
  list.sort((a, b) => interest(b) - interest(a));
  const chosen = [];
  for (const p of list) {
    if (seenCodes.has(p.code)) continue;
    const first = p.sol[0].join(',');
    const close = (q) => q.turn !== undefined && p.turn !== undefined && Math.abs(q.turn - p.turn) < 3;
    if (chosen.some((q) => close(q) || q.sol[0].join(',') === first)) continue;
    chosen.push(p);
    seenCodes.add(p.code);
  }
  fresh.push(...chosen);
}

// Easier: several different first edges reach the best. Harder: one pair
// does it, and it both fences in area and cuts, or the swing is large.
const level = (p) => {
  const t = typeOf(p);
  if (t === 'plan') return 3;
  if (t === 'block') return p.count <= 2 ? 3 : p.count <= 6 ? 2 : 1;
  if (t !== 'swing') return p.firsts > 2 ? 1 : (p.best - p.greedy >= 3 || p.firsts === 1) ? 3 : 2;
  if (p.firsts > 2) return 1;
  if ((p.gain > 1e-9 && p.cut > 1e-9) || p.best >= 15) return 3;
  return 2;
};
fresh.sort((a, b) => level(a) - level(b) || a.best - b.best);

const keep = ['type', 'code', 'player', 'best', 'greedy', 'worst', 'count', 'gain', 'cut', 'firsts', 'level', 'sol'];
const clean = (p) => {
  const o = {};
  for (const k of keep) if (p[k] !== undefined) o[k] = p[k];
  if (o.type === 'swing') delete o.type;
  return o;
};
const out = [...existing.map(clean), ...fresh.map((p) => clean({ ...p, level: level(p) }))];
writeFileSync(new URL('../js/puzzledata.js', import.meta.url), `// Generated by tools/build-puzzles.mjs from mined positions. Every answer
// was confirmed by tools/verify-puzzles.mjs on the engine alone.
export const PUZZLES = ${JSON.stringify(out, null, 0).replace(/\},\{/g, '},\n  {').replace(/^\[\{/, '[\n  {').replace(/\}\]$/, '},\n]')};
`);
const types = ['swing', 'gain', 'cut', 'block', 'plan'];
console.log(`${all.length} candidates, ${fresh.length} new, ${out.length} puzzles: ${types.map((t) => `${t} ${out.filter((p) => typeOf(p) === t).length}`).join(', ')}`);
